### PR TITLE
docs: added prop table for TopBar component

### PR DESCRIPTION
**Pull request by Ananyamadhu08**
- added prop table for TopBar component for https://github.com/dequelabs/cauldron/issues/806 this issue

### CODE REVIEW

**Comment by abbeyperini-deque** [comment]
This has uncaught errors when I try to run it.

You'll need to import `PropDocs` to use it.

You'll need to import `children` and `className` from `props.js` if you want to use them.

**Comment by Ananyamadhu08** [comment]
Have fixed the issue, please take a look.

**Comment by abbeyperini-deque** [comment]
🚨 reviewed for security 🚨

**Review by abbeyperini-deque — APPROVED** [review]
Looking good! Thanks!

Screen Shot 2022-10-19 at 6 41 32 PM

**Pull request merged**
