### PR TITLE
fix(IconButton): sets aria-label when disabled

### LINKED ISSUE #309: IconButton with label has no accessible name if the tooltip has not been created
Solution: Set the `aria-label` on the button _only_ when the button is currently disabled.

### PR DESCRIPTION
**Pull request by schne324**
Closes #309

### CODE REVIEW

**Review by scurker — COMMENTED** [review]
I think we're missing one thing here.

The tooltip adds a dynamic attribute according to its `association` prop. We should probably make it so that when it becomes unmounted or the association changes it removes the dynamic prop from the Button.

https://github.com/dequelabs/cauldron/blob/3ad6ac953a2f500dfe63d9592d962af80f5438f5/packages/react/src/components/Tooltip/index.tsx#L174-L182

**Comment by schne324** [comment]
I don't think so...we literally don't render the tooltip when disabled: https://github.com/dequelabs/cauldron/blob/eb0d7b059034998e8081e7053a5f38e1bb87ba4e/packages/react/src/components/IconButton/index.tsx#L54-L63

**Comment by scurker** [comment]
Steps where this could happen:

1. IconButton gets mounted with no `disabled`
1. IconButton gets focused/hovered and Tooltip is created that adds `association` attribute value to the target button element
1. IconButton then gets disabled, removing the tooltip
1. The IconButton has both `aria-label` and the `association` that was dynamically added via the Tooltip

**Comment by schne324** [comment]
> Steps where this could happen

Yea good catch! This one might be tricky... 🤔

**Pull request closed without merging**
