### PR TITLE
fix: page title is not updated when navigating directly to a component page

### LINKED ISSUE #787: Page title is not updated when navigating directly to a component page
image

can reproduce by navigating directly to a component page, like https://cauldron.dequelabs.com/components/Checkbox for example...OR the user right-clicks on any navigational link and opens the page in a new window

In [docs/index.js](https://github.com/dequelabs/cauldron/blob/develop/docs/index.js), we use the [react-helmet](https://www.npmjs.com/package/react-helmet) to dynamically update the page title.

### PR DESCRIPTION
**Pull request by nikolaps17**
Fixed #787

### CODE REVIEW

**Comment by abbeyperini-deque** [comment]
🚨 reviewed for security 🚨

**Comment by abbeyperini-deque** [comment]
Love this solution!

Only thing is it's currently overriding the [dynamic description](https://github.com/dequelabs/cauldron/blob/fd9dbc87df439c53b42560e7d7067174179ae6f5/docs/index.js#L145).

**Comment by nikolaps17** [comment]
Sorry, my bad. I didn't notice. I'm going to fix it.

**Comment by nikolaps17** [comment]
@abbeyperini-deque That should do it.

**Comment by abbeyperini-deque** [comment]
🚨 reviewed for security 🚨

**Comment by abbeyperini-deque** [comment]
https://user-images.githubusercontent.com/99676396/197260322-270f7e88-7122-4716-ac81-05bd21227b5b.mov

**Review by abbeyperini-deque — APPROVED** [review]
A lovely refactor! Thank you!

**Pull request merged**
