### PR TITLE
docs: added PropDocs component in OptionsMenu component page

### PR DESCRIPTION
**Pull request by VedanthB**
Added PropDocs component in OptionsMenu component page for this issue https://github.com/dequelabs/cauldron/issues/805

### CODE REVIEW

**Comment by abbeyperini-deque** [comment]
🚨 reviewed for security 🚨

**Comment by abbeyperini-deque** [comment]
Hey Vendath,

The OptionsMenu component has a few more props than just children and classname - 
https://github.com/dequelabs/cauldron/blob/dcc3921f2bae7576de0c594738436eacb7ad20a0/packages/react/src/components/OptionsMenu/OptionsMenu.tsx#L49

It also looks like you've committed changes to the `package.json` and `yarn.lock` that we don't need.

**Comment by VedanthB** [comment]
> Hey Vendath,
> 
> The OptionsMenu component has a few more props than just children and classname -
> 
> https://github.com/dequelabs/cauldron/blob/dcc3921f2bae7576de0c594738436eacb7ad20a0/packages/react/src/components/OptionsMenu/OptionsMenu.tsx#L49
> 
> It also looks like you've committed changes to the `package.json` and `yarn.lock` that we don't need.

I have added the option menu props and  uncommitted changes to the `package.json` and `yarn.lock`. Please review

**Comment by abbeyperini-deque** [comment]
Great start! We can flesh out the details a bit more and children is required in this one. You can remove the `children` prop import and use this:

             ```
             children: {
                 type: 'node',
                 description: 'The child content',
                 required: true
             },
             onClose: {
                type: 'function',
                description: 'Function called when the OptionMenu component is closed.',
                default: '() => {}'
              },
              onSelect: {
                type: 'function',
                description: 'Function called when a child of the OptionMenu component is selected.',
                default: '() => {}'
              },
              trigger: {
                type: 'node',
                description: 'Pass an element that will display when the OptionsMenu component is closed and open it when activated.'
              },
              closeOnSelect: {
                type: 'boolean',
                description: ''
              },
              menuRef: {
                type: ' function or function.current',
                description: 'Pass a ref to the OptionsMenu'
              },
              align: {
                type: 'string',
                description: 'Style your OptionsMenu to align left or right',
                default: 'right'
              },
              show: {
                type: 'boolean',
                description: 'Whether or not to show the opened OptionsMenu'
              },
              id: {
                type: 'string',
                description: 'ID string'
               }
              ```

**Comment by VedanthB** [comment]
> children: {
>              type: 'node',
>              description: 'The child content',
>              required: true
>          },
>          onClose: {
>             type: 'function',
>             description: 'Function called when the OptionMenu component is closed.',
>             default: '() => {}'
>           },
>           onSelect: {
>             type: 'function',
>             description: 'Function called when a child of the OptionMenu component is selected.',
>             default: '() => {}'
>           },
>           trigger: {
>             type: 'node',
>             description: 'Pass an element that will display when the OptionsMenu component is closed and open it when activated.'
>           },
>           closeOnSelect: {
>             type: 'boolean',
>             description: ''
>           },
>           menuRef: {
>             type: ' function or function.current',
>             description: 'Pass a ref to the OptionsMenu'
>           },
>           align: {
>             type: 'string',
>             description: 'Style your OptionsMenu to align left or right',
>             default: 'right'
>           },
>           show: {
>             type: 'boolean',
>             description: 'Whether or not to show the opened OptionsMenu'
>           },
>           id: {
>             type: 'string',
>             description: 'ID string'
>            }

I have added these changes, please review.

**Comment by VedanthB** [comment]
> > children: {
> > type: 'node',
> > description: 'The child content',
> > required: true
> > },
> > onClose: {
> > type: 'function',
> > description: 'Function called when the OptionMenu component is closed.',
> > default: '() => {}'
> > },
> > onSelect: {
> > type: 'function',
> > description: 'Function called when a child of the OptionMenu component is selected.',
> > default: '() => {}'
> > },
> > trigger: {
> > type: 'node',
> > description: 'Pass an element that will display when the OptionsMenu component is closed and open it when activated.'
> > },
> > closeOnSelect: {
> > type: 'boolean',
> > description: ''
> > },
> > menuRef: {
> > type: ' function or function.current',
> > description: 'Pass a ref to the OptionsMenu'
> > },
> > align: {
> > type: 'string',
> > description: 'Style your OptionsMenu to align left or right',
> > default: 'right'
> > },
> > show: {
> > type: 'boolean',
> > description: 'Whether or not to show the opened OptionsMenu'
> > },
> > id: {
> > type: 'string',
> > description: 'ID string'
> > }
> 
> I have added these changes, please review. @abbeyperini-deque

**Comment by abbeyperini-deque** [comment]
🚨 reviewed for security 🚨

**Review by abbeyperini-deque — APPROVED** [review]
Approved! Thanks for your contribution!

**Pull request merged**
